### ISSUE TITLE
The library requires urllib3 2.0.0 or above

### ISSUE THREAD

**Issue by justanotherboy** [thousandeyes/thousandeyes-sdk-python#41]
All the modules of thousandeyes-sdk-python list urllib3 >= 1.25.3 when in reality the minimum required version is 2.0.0.

When trying to import something from the core library using urllib3 < 2.0.0 it throws an ImportError:

```
>>> from thousandeyes-sdk.core import Configuration
  File "<stdin>", line 1
    from thousandeyes-sdk.core import Configuration
                     ^
SyntaxError: invalid syntax
>>> from thousandeyes_sdk.core import Configuration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marianl2/repo/de-toolbox/.venv/lib/python3.10/site-packages/thousandeyes_sdk/core/__init__.py", line 18, in <module>
    from .api_client import ApiClient
  File "/Users/marianl2/repo/de-toolbox/.venv/lib/python3.10/site-packages/thousandeyes_sdk/core/api_client.py", line 31, in <module>
    from thousandeyes_sdk.core.configuration import Configuration
  File "/Users/marianl2/repo/de-toolbox/.venv/lib/python3.10/site-packages/thousandeyes_sdk/core/configuration.py", line 27, in <module>
    from thousandeyes_sdk.core.thousandeyes_retry import ThousandEyesRetry
  File "/Users/marianl2/repo/de-toolbox/.venv/lib/python3.10/site-packages/thousandeyes_sdk/core/thousandeyes_retry.py", line 21, in <module>
    from urllib3 import BaseHTTPResponse
ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3' (/Users/marianl2/repo/de-toolbox/.venv/lib/python3.10/site-packages/urllib3/__init__.py)
```

Can you please update the dependencies of the library?

**Comment by joaomper-TE** [comment]
Hey @justanotherboy and thanks for reporting. You are correct, we must have missed that.

Will correct and let you know.
